# Generated by Django 5.0.6 on 2024-06-01 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_remove_wishlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='wishlist',
        ),
    ]
