# Generated by Django 5.0.6 on 2024-06-01 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_remove_wishlistitem_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
